# Generated by Django 5.2.1 on 2025-06-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_comments_total_comment_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='author',
        ),
    ]
