# Generated by Django 5.2.1 on 2025-06-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_commented_by_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
