# Generated by Django 5.2.1 on 2025-06-10 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0008_trend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.CharField(choices=[('newfriendreq', 'New Friend Request'), ('acceptedfriendreq', 'Accepted Friend Request'), ('rejectedfriendreq', 'Rejected Friend Request'), ('postlike', 'Post Like'), ('postcomment', 'Post Comment')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notify', to=settings.AUTH_USER_MODEL)),
                ('create_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_notify', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
